v20210201

diff --git a/packages/bsp/common/usr/lib/armbian/armbian-firstlogin b/packages/bsp/common/usr/lib/armbian/armbian-firstlogin
--- a/packages/bsp/common/usr/lib/armbian/armbian-firstlogin
+++ b/packages/bsp/common/usr/lib/armbian/armbian-firstlogin
@@ -12,6 +12,9 @@ check_abort()
 {
 	echo -e "\nDisabling user account creation procedure\n"
 	rm -f /root/.not_logged_in_yet
+	if [[ ${USER_SHELL} == zsh ]]; then
+		printf "\nYou selected \e[0;91mZSH\x1B[0m as your default shell. If you want to use it right away, please logout and login! \n\n"
+	fi
 	trap - INT
 	exit 0
 }
@@ -32,6 +35,39 @@ do
 done
 }
 
+set_shell()
+{
+
+	optionsAudits=($(cat /etc/shells | grep "zsh\|/bash" | sed 's/\/bin\///g' | sed 's/\/usr//g' | uniq))
+	USER_SHELL="bash"
+
+	if [[ "${#optionsAudits[@]}" -gt 1 ]]; then
+		while :
+			do
+				i=1
+				echo -e "\nChoose default system command shell:\n"
+				for o in  "${optionsAudits[@]}"; do
+					echo "$i) $o"
+					let i++
+				done
+				read -n1 -s reply
+				case $reply in
+					"1"|"${optionsAudits[0]}") USER_SHELL="${optionsAudits[0]}"; break;;
+					"2"|"${optionsAudits[1]}") USER_SHELL="${optionsAudits[1]}"; break;;
+					*) USER_SHELL="${optionsAudits[0]}"; break;;
+				esac
+			done
+	fi
+	SHELL_PATH=$(grep /$USER_SHELL$ /etc/shells | tail -1)
+
+	chsh -s $(grep -iF "/$USER_SHELL" /etc/shells | tail -1)
+	echo -e "\nShell: \x1B[92m${USER_SHELL^^}\x1B[0m"
+
+	# change shell for future users
+	sed -i "s|^SHELL=.*|SHELL=${SHELL_PATH}|" /etc/default/useradd
+	sed -i "s|^DSHELL=.*|DSHELL=${SHELL_PATH}|" /etc/adduser.conf
+
+}
 
 set_timezone_and_locales()
 {
@@ -39,55 +75,66 @@ set_timezone_and_locales()
 	# Grab this machine's public IP address
 	PUBLIC_IP=`curl --max-time 5 -s https://ipinfo.io/ip`
 	if [ $? -eq 0 ]; then
+		read -n1 -s -r -p "Set user language based on your location? [Y/n] " response
+		echo ""
+		if [[ "${response}" =~ ^(Y|y|"")$ ]]; then
 
-		# Call the geolocation API and capture the output
-		RES=$(
-				curl --max-time 5 -s http://ipwhois.app/json/${PUBLIC_IP} | \
-				jq '.timezone, .country, .country_code' | \
-				while read -r TIMEZONE; do
-					read -r COUNTRY
-					echo "${TIMEZONE},${COUNTRY},${COUNTRYCODE}" | tr --delete \"
-				done
-			)
+			# Call the geolocation API and capture the output
+			RES=$(
+					curl --max-time 5 -s http://ipwhois.app/json/${PUBLIC_IP} | \
+					jq '.timezone, .country, .country_code' | \
+					while read -r TIMEZONE; do
+						read -r COUNTRY
+						echo "${TIMEZONE},${COUNTRY},${COUNTRYCODE}" | tr --delete \"
+					done
+				)
 
-		TZDATA=$(echo ${RES} | cut -d"," -f1)
-		STATE=$(echo ${RES} | cut -d"," -f2)
-		LOCALES=$(grep territory /usr/share/i18n/locales/* | grep "$STATE" | cut -d ":" -f 1 | cut -d "/" -f 6 |  xargs -I{} grep {} /usr/share/i18n/SUPPORTED | grep "\.UTF-8" | cut -d " " -f 1)
-		# UTF8 is not present everywhere so check again in case it returns empty value
-		[[ -z "$LOCALES" ]] && LOCALES=$(grep territory /usr/share/i18n/locales/* | grep "$STATE" | cut -d ":" -f 1 | cut -d "/" -f 6 |  xargs -I{} grep {} /usr/share/i18n/SUPPORTED | cut -d " " -f 1)
-		CCODE=$(echo ${RES} | cut -d"," -f3 | awk '{print tolower($0)}' | xargs)
-		options=(`echo ${LOCALES}`);
+			TZDATA=$(echo ${RES} | cut -d"," -f1)
+			STATE=$(echo ${RES} | cut -d"," -f2)
+			CCODE=$(echo ${RES} | cut -d"," -f3 | xargs)
+			KEYBOARD="${CCODE,,}"
+			LOCALES=$(grep territory /usr/share/i18n/locales/* | grep "$CCODE" | cut -d ":" -f 1 | cut -d "/" -f 6 |  xargs -I{} grep {} /usr/share/i18n/SUPPORTED | grep "\.UTF-8" | cut -d " " -f 1)
+			# UTF8 is not present everywhere so check again in case it returns empty value
+			[[ -z "$LOCALES" ]] && LOCALES=$(grep territory /usr/share/i18n/locales/* | grep "$CCODE" | cut -d ":" -f 1 | cut -d "/" -f 6 |  xargs -I{} grep {} /usr/share/i18n/SUPPORTED | cut -d " " -f 1)
 
-		# reconfigure tzdata
-		timedatectl set-timezone "${TZDATA}"
-		dpkg-reconfigure --frontend=noninteractive tzdata > /dev/null 2>&1
+			# change it only if we have a match
+			if [[ -n "$LOCALES" ]]; then
 
-		echo -e "Detected timezone: \x1B[92m$(LC_ALL=C timedatectl | grep "Time zone" | cut -d":" -f2 | xargs)\x1B[0m"
-		# when having more locales, prompt for choosing one
-		if [[ "${#options[@]}" -gt 1 ]]; then
-			echo ""
-			echo -e "\nAt your location, more locales are possible:\n"
-			PS3='Please enter your choice:'
-			select opt in "${options[@]}"
-			do
-				if [[ " ${options[@]} " =~ " ${opt} " ]]; then
-					LOCALES=${opt}
-					break
+				options=(`echo ${LOCALES}`);
+
+				# reconfigure tzdata
+				timedatectl set-timezone "${TZDATA}"
+				dpkg-reconfigure --frontend=noninteractive tzdata > /dev/null 2>&1
+
+				echo -e "Detected timezone: \x1B[92m$(LC_ALL=C timedatectl | grep "Time zone" | cut -d":" -f2 | xargs)\x1B[0m"
+
+				# when having more locales, prompt for choosing one
+				if [[ "${#options[@]}" -gt 1 ]]; then
+					echo ""
+					echo -e "\nAt your location, more locales are possible:\n"
+					PS3='Please enter your choice:'
+					select opt in "${options[@]}"
+					do
+						if [[ " ${options[@]} " =~ " ${opt} " ]]; then
+							LOCALES=${opt}
+							break
+						fi
+					done
 				fi
-			done
-		fi
 
-		# generate locales
-		sed -i 's/# '"${LOCALES}"'/'"${LOCALES}"'/' /etc/locale.gen
-		echo -e "Generating locales: \x1B[92m${LOCALES}\x1B[0m"
-		locale-gen $LOCALES > /dev/null 2>&1
+				# generate locales
+				sed -i 's/# '"${LOCALES}"'/'"${LOCALES}"'/' /etc/locale.gen
+				echo -e "Generating locales: \x1B[92m${LOCALES}\x1B[0m"
+				locale-gen $LOCALES > /dev/null 2>&1
 
-		# adding another keyboard layout
-		if grep -q " $CCODE " /usr/share/X11/xkb/rules/base.lst ; then
-			echo -e "Adding console keyboard layout: \x1B[92m$CCODE\x1B[0m"
-			CCODE=$(cat /etc/default/keyboard | grep XKBLAYOUT | awk -F'"' '$0=$2')",$CCODE"
-			sed -i "s/XKBLAYOUT=.*/XKBLAYOUT=\"$CCODE\"/" /etc/default/keyboard
-			setupcon -k --force
+				# adding another keyboard layout
+				if grep -q " $CCODE " /usr/share/X11/xkb/rules/base.lst ; then
+					echo -e "Adding console keyboard layout: \x1B[92m$CCODE\x1B[0m"
+					CCODE=$(cat /etc/default/keyboard | grep XKBLAYOUT | awk -F'"' '$0=$2')",$CCODE"
+					sed -i "s/XKBLAYOUT=.*/XKBLAYOUT=\"$KEYBOARD\"/" /etc/default/keyboard
+					setupcon -k --force
+				fi
+			fi
 		fi
 	fi
 
@@ -142,9 +189,9 @@ add_user()
                         result="$(cracklib-check <<<"$password")"
                         okay="$(awk -F': ' '{ print $2}' <<<"$result")"
                         if [[ "$okay" == "OK" ]]; then
-				echo -e "\nPlease provide your real name (eg. John Doe): \c"
-		                read -e RealName
-				adduser --quiet --disabled-password --shell /bin/bash --home /home/"$RealUserName" --gecos "$RealName" "$RealUserName"
+				echo -e ""
+				read -e -p "Please provide your real name: " -i "${RealUserName^}" RealName
+				adduser --quiet --disabled-password --home /home/"$RealUserName" --gecos "$RealName" "$RealUserName"
 				(echo $first_input;echo $second_input;) | passwd "$RealUserName" >/dev/null 2>&1
 				for additionalgroup in sudo netdev audio video disk tty users games dialout plugdev input bluetooth systemd-journal ssh; do
 					usermod -aG ${additionalgroup} ${RealUserName} 2>/dev/null
@@ -188,7 +235,6 @@ add_user()
 }
 
 if [[ -f /root/.not_logged_in_yet && -n $(tty) ]]; then
-
 	# disable autologin
 	rm -f /etc/systemd/system/getty@.service.d/override.conf
 	rm -f /etc/systemd/system/serial-getty@.service.d/override.conf
@@ -235,7 +281,6 @@ if [[ -f /root/.not_logged_in_yet && -n $(tty) ]]; then
 			okay="$(awk -F': ' '{ print $2}' <<<"$result")"
 			if [[ "$okay" == "OK" ]]; then
 				(echo $first_input;echo $second_input;) | passwd root >/dev/null 2>&1
-				set_timezone_and_locales
 				break
 				else
 				echo -e "Rejected - \e[0;31m$okay.\x1B[0m Try again."
@@ -246,13 +291,28 @@ if [[ -f /root/.not_logged_in_yet && -n $(tty) ]]; then
 	done
 	trap - INT TERM EXIT
 
+	# ask user to select shell
+	trap '' 2
+	set_shell
+	trap - INT TERM EXIT
+
 	trap check_abort INT
+
 	while [ -f "/root/.not_logged_in_yet" ]; do
 		echo -e "\nCreating a new user account. Press <Ctrl-C> to abort"
-		[ -n "$desktop_lightdm" ] && echo "Desktop environment will not be enabled if you abort the new user creation"
+		[ -n "$desktop_lightdm" ] && echo -e "\n\e[0;31mDesktop environment will not be enabled if you abort the new user creation\x1B[0m"
 		add_user
 	done
 	trap - INT TERM EXIT
+
+	# ask user to select automated locales or not
+	trap '' 2
+	set_timezone_and_locales
+	trap - INT TERM EXIT
+
+	if [[ ${USER_SHELL} == zsh ]]; then
+		printf "\nYou selected \e[0;91mZSH\x1B[0m as your default shell. If you want to use it right away, please logout and login! \n\n"
+	fi
 
 	# check whether desktop environment has to be considered
 	if [ -n "$desktop_lightdm" ] && [ -n "$RealName" ] ; then
@@ -278,7 +338,8 @@ if [[ -f /root/.not_logged_in_yet && -n $(tty) ]]; then
 			if [ -f /root/.desktop_autologin ]; then
 				rm /root/.desktop_autologin
 			else
-				(sleep 20; rm /etc/lightdm/lightdm.conf.d/22-armbian-autologin.conf) &
+				systemctl -q enable armbian-disable-autologin.timer
+				systemctl start armbian-disable-autologin.timer
 			fi
 			# logout if logged at console
 			[[ -n $(who -la | grep root | grep tty1) ]] && exit 1
@@ -290,5 +351,5 @@ if [[ -f /root/.not_logged_in_yet && -n $(tty) ]]; then
 			printf "\e[0;91mPlease reboot the system now \x1B[0m \n\n"
 		fi
 	fi
-	export TERM=linux
+
 fi
